# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cobotta2.server_grpc import joypad_pb2 as joypad__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in joypad_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JoyPadControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDpose = channel.unary_unary(
                '/cobotta.JoyPadControl/SendDpose',
                request_serializer=joypad__pb2.SendDposeRequest.SerializeToString,
                response_deserializer=joypad__pb2.SendDposeResponse.FromString,
                _registered_method=True)
        self.Halt = channel.unary_unary(
                '/cobotta.JoyPadControl/Halt',
                request_serializer=joypad__pb2.HaltRequest.SerializeToString,
                response_deserializer=joypad__pb2.HaltResponse.FromString,
                _registered_method=True)
        self.JoypadStart = channel.unary_unary(
                '/cobotta.JoyPadControl/JoypadStart',
                request_serializer=joypad__pb2.JoypadStartRequest.SerializeToString,
                response_deserializer=joypad__pb2.JoypadStartResponse.FromString,
                _registered_method=True)
        self.JoypadStop = channel.unary_unary(
                '/cobotta.JoyPadControl/JoypadStop',
                request_serializer=joypad__pb2.JoypadStopRequest.SerializeToString,
                response_deserializer=joypad__pb2.JoypadStopResponse.FromString,
                _registered_method=True)
        self.JoypadSetScale = channel.unary_unary(
                '/cobotta.JoyPadControl/JoypadSetScale',
                request_serializer=joypad__pb2.JoypadSetScaleRequest.SerializeToString,
                response_deserializer=joypad__pb2.JoypadSetScaleResponse.FromString,
                _registered_method=True)
        self.JoypadSetDt = channel.unary_unary(
                '/cobotta.JoyPadControl/JoypadSetDt',
                request_serializer=joypad__pb2.JoypadSetDtRequest.SerializeToString,
                response_deserializer=joypad__pb2.JoypadSetDtResponse.FromString,
                _registered_method=True)
        self.GetCurrentPosition = channel.unary_unary(
                '/cobotta.JoyPadControl/GetCurrentPosition',
                request_serializer=joypad__pb2.GetCurrentPositionRequest.SerializeToString,
                response_deserializer=joypad__pb2.GetCurrentPositionResponse.FromString,
                _registered_method=True)
        self.GetCurrentAngle = channel.unary_unary(
                '/cobotta.JoyPadControl/GetCurrentAngle',
                request_serializer=joypad__pb2.GetCurrentAngleRequest.SerializeToString,
                response_deserializer=joypad__pb2.GetCurrentAngleResponse.FromString,
                _registered_method=True)
        self.GetValue = channel.unary_unary(
                '/cobotta.JoyPadControl/GetValue',
                request_serializer=joypad__pb2.VarGetRequest.SerializeToString,
                response_deserializer=joypad__pb2.VarGetResponse.FromString,
                _registered_method=True)
        self.PutValue = channel.unary_unary(
                '/cobotta.JoyPadControl/PutValue',
                request_serializer=joypad__pb2.VarPutRequest.SerializeToString,
                response_deserializer=joypad__pb2.VarPutResponse.FromString,
                _registered_method=True)
        self.MotorOn = channel.unary_unary(
                '/cobotta.JoyPadControl/MotorOn',
                request_serializer=joypad__pb2.MotorOnRequest.SerializeToString,
                response_deserializer=joypad__pb2.MotorOnResponse.FromString,
                _registered_method=True)
        self.MotorOff = channel.unary_unary(
                '/cobotta.JoyPadControl/MotorOff',
                request_serializer=joypad__pb2.MotorOffRequest.SerializeToString,
                response_deserializer=joypad__pb2.MotorOffResponse.FromString,
                _registered_method=True)
        self.HandMoveH = channel.unary_unary(
                '/cobotta.JoyPadControl/HandMoveH',
                request_serializer=joypad__pb2.HandMoveHRequest.SerializeToString,
                response_deserializer=joypad__pb2.HandMoveHResponse.FromString,
                _registered_method=True)
        self.HandMoveA = channel.unary_unary(
                '/cobotta.JoyPadControl/HandMoveA',
                request_serializer=joypad__pb2.HandMoveARequest.SerializeToString,
                response_deserializer=joypad__pb2.HandMoveAResponse.FromString,
                _registered_method=True)
        self.MovePose = channel.unary_unary(
                '/cobotta.JoyPadControl/MovePose',
                request_serializer=joypad__pb2.MovePoseRequest.SerializeToString,
                response_deserializer=joypad__pb2.MovePoseResponse.FromString,
                _registered_method=True)
        self.MoveP = channel.unary_unary(
                '/cobotta.JoyPadControl/MoveP',
                request_serializer=joypad__pb2.MovePRequest.SerializeToString,
                response_deserializer=joypad__pb2.MovePResponse.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/cobotta.JoyPadControl/Move',
                request_serializer=joypad__pb2.MoveRequest.SerializeToString,
                response_deserializer=joypad__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.TakeArm = channel.unary_unary(
                '/cobotta.JoyPadControl/TakeArm',
                request_serializer=joypad__pb2.TakeArmRequest.SerializeToString,
                response_deserializer=joypad__pb2.TakeArmResponse.FromString,
                _registered_method=True)
        self.GiveArm = channel.unary_unary(
                '/cobotta.JoyPadControl/GiveArm',
                request_serializer=joypad__pb2.GiveArmRequest.SerializeToString,
                response_deserializer=joypad__pb2.GiveArmResponse.FromString,
                _registered_method=True)
        self.GetErrorCount = channel.unary_unary(
                '/cobotta.JoyPadControl/GetErrorCount',
                request_serializer=joypad__pb2.GetErrorCountRequest.SerializeToString,
                response_deserializer=joypad__pb2.GetErrorCountResponse.FromString,
                _registered_method=True)
        self.GetErrorDescription = channel.unary_unary(
                '/cobotta.JoyPadControl/GetErrorDescription',
                request_serializer=joypad__pb2.GetErrorDescriptionRequest.SerializeToString,
                response_deserializer=joypad__pb2.GetErrorDescriptionResponse.FromString,
                _registered_method=True)
        self.GetErrorInfo = channel.unary_unary(
                '/cobotta.JoyPadControl/GetErrorInfo',
                request_serializer=joypad__pb2.GetErrorInfoRequest.SerializeToString,
                response_deserializer=joypad__pb2.GetErrorInfoResponse.FromString,
                _registered_method=True)
        self.GetCurrentErrorInfo = channel.unary_unary(
                '/cobotta.JoyPadControl/GetCurrentErrorInfo',
                request_serializer=joypad__pb2.GetCurrentErrorInfoRequest.SerializeToString,
                response_deserializer=joypad__pb2.GetCurrentErrorInfoResponse.FromString,
                _registered_method=True)
        self.ResetError = channel.unary_unary(
                '/cobotta.JoyPadControl/ResetError',
                request_serializer=joypad__pb2.ResetErrorRequest.SerializeToString,
                response_deserializer=joypad__pb2.ResetErrorResponse.FromString,
                _registered_method=True)


class JoyPadControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDpose(self, request, context):
        """--- JoyPad pose
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Halt(self, request, context):
        """--- JoyPad 移動命令のキャンセル
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoypadStart(self, request, context):
        """---- JoyPatRuntime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoypadStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoypadSetScale(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoypadSetDt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentPosition(self, request, context):
        """---- 情報系
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentAngle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValue(self, request, context):
        """--- 内部変数の取り扱い
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MotorOn(self, request, context):
        """---- Motor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MotorOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandMoveH(self, request, context):
        """---- Hand
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandMoveA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MovePose(self, request, context):
        """---- Move 系（CobottaJoyPad.move_pose / move_p_index / move 用）
        座標位置指定
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveP(self, request, context):
        """座標番号指定
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """上位系API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeArm(self, request, context):
        """---- Arm 権限制御
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GiveArm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorCount(self, request, context):
        """---- Error 処理
        任意の error_code から説明文字列を取得
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorInfo(self, request, context):
        """ある番号でのエラー
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentErrorInfo(self, request, context):
        """現在のエラー
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetError(self, request, context):
        """RC8 側のエラーリセット（ManualResetPreparation + ClearError + α）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JoyPadControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDpose': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDpose,
                    request_deserializer=joypad__pb2.SendDposeRequest.FromString,
                    response_serializer=joypad__pb2.SendDposeResponse.SerializeToString,
            ),
            'Halt': grpc.unary_unary_rpc_method_handler(
                    servicer.Halt,
                    request_deserializer=joypad__pb2.HaltRequest.FromString,
                    response_serializer=joypad__pb2.HaltResponse.SerializeToString,
            ),
            'JoypadStart': grpc.unary_unary_rpc_method_handler(
                    servicer.JoypadStart,
                    request_deserializer=joypad__pb2.JoypadStartRequest.FromString,
                    response_serializer=joypad__pb2.JoypadStartResponse.SerializeToString,
            ),
            'JoypadStop': grpc.unary_unary_rpc_method_handler(
                    servicer.JoypadStop,
                    request_deserializer=joypad__pb2.JoypadStopRequest.FromString,
                    response_serializer=joypad__pb2.JoypadStopResponse.SerializeToString,
            ),
            'JoypadSetScale': grpc.unary_unary_rpc_method_handler(
                    servicer.JoypadSetScale,
                    request_deserializer=joypad__pb2.JoypadSetScaleRequest.FromString,
                    response_serializer=joypad__pb2.JoypadSetScaleResponse.SerializeToString,
            ),
            'JoypadSetDt': grpc.unary_unary_rpc_method_handler(
                    servicer.JoypadSetDt,
                    request_deserializer=joypad__pb2.JoypadSetDtRequest.FromString,
                    response_serializer=joypad__pb2.JoypadSetDtResponse.SerializeToString,
            ),
            'GetCurrentPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentPosition,
                    request_deserializer=joypad__pb2.GetCurrentPositionRequest.FromString,
                    response_serializer=joypad__pb2.GetCurrentPositionResponse.SerializeToString,
            ),
            'GetCurrentAngle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentAngle,
                    request_deserializer=joypad__pb2.GetCurrentAngleRequest.FromString,
                    response_serializer=joypad__pb2.GetCurrentAngleResponse.SerializeToString,
            ),
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=joypad__pb2.VarGetRequest.FromString,
                    response_serializer=joypad__pb2.VarGetResponse.SerializeToString,
            ),
            'PutValue': grpc.unary_unary_rpc_method_handler(
                    servicer.PutValue,
                    request_deserializer=joypad__pb2.VarPutRequest.FromString,
                    response_serializer=joypad__pb2.VarPutResponse.SerializeToString,
            ),
            'MotorOn': grpc.unary_unary_rpc_method_handler(
                    servicer.MotorOn,
                    request_deserializer=joypad__pb2.MotorOnRequest.FromString,
                    response_serializer=joypad__pb2.MotorOnResponse.SerializeToString,
            ),
            'MotorOff': grpc.unary_unary_rpc_method_handler(
                    servicer.MotorOff,
                    request_deserializer=joypad__pb2.MotorOffRequest.FromString,
                    response_serializer=joypad__pb2.MotorOffResponse.SerializeToString,
            ),
            'HandMoveH': grpc.unary_unary_rpc_method_handler(
                    servicer.HandMoveH,
                    request_deserializer=joypad__pb2.HandMoveHRequest.FromString,
                    response_serializer=joypad__pb2.HandMoveHResponse.SerializeToString,
            ),
            'HandMoveA': grpc.unary_unary_rpc_method_handler(
                    servicer.HandMoveA,
                    request_deserializer=joypad__pb2.HandMoveARequest.FromString,
                    response_serializer=joypad__pb2.HandMoveAResponse.SerializeToString,
            ),
            'MovePose': grpc.unary_unary_rpc_method_handler(
                    servicer.MovePose,
                    request_deserializer=joypad__pb2.MovePoseRequest.FromString,
                    response_serializer=joypad__pb2.MovePoseResponse.SerializeToString,
            ),
            'MoveP': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveP,
                    request_deserializer=joypad__pb2.MovePRequest.FromString,
                    response_serializer=joypad__pb2.MovePResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=joypad__pb2.MoveRequest.FromString,
                    response_serializer=joypad__pb2.MoveResponse.SerializeToString,
            ),
            'TakeArm': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeArm,
                    request_deserializer=joypad__pb2.TakeArmRequest.FromString,
                    response_serializer=joypad__pb2.TakeArmResponse.SerializeToString,
            ),
            'GiveArm': grpc.unary_unary_rpc_method_handler(
                    servicer.GiveArm,
                    request_deserializer=joypad__pb2.GiveArmRequest.FromString,
                    response_serializer=joypad__pb2.GiveArmResponse.SerializeToString,
            ),
            'GetErrorCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorCount,
                    request_deserializer=joypad__pb2.GetErrorCountRequest.FromString,
                    response_serializer=joypad__pb2.GetErrorCountResponse.SerializeToString,
            ),
            'GetErrorDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorDescription,
                    request_deserializer=joypad__pb2.GetErrorDescriptionRequest.FromString,
                    response_serializer=joypad__pb2.GetErrorDescriptionResponse.SerializeToString,
            ),
            'GetErrorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorInfo,
                    request_deserializer=joypad__pb2.GetErrorInfoRequest.FromString,
                    response_serializer=joypad__pb2.GetErrorInfoResponse.SerializeToString,
            ),
            'GetCurrentErrorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentErrorInfo,
                    request_deserializer=joypad__pb2.GetCurrentErrorInfoRequest.FromString,
                    response_serializer=joypad__pb2.GetCurrentErrorInfoResponse.SerializeToString,
            ),
            'ResetError': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetError,
                    request_deserializer=joypad__pb2.ResetErrorRequest.FromString,
                    response_serializer=joypad__pb2.ResetErrorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cobotta.JoyPadControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cobotta.JoyPadControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JoyPadControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDpose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/SendDpose',
            joypad__pb2.SendDposeRequest.SerializeToString,
            joypad__pb2.SendDposeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Halt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/Halt',
            joypad__pb2.HaltRequest.SerializeToString,
            joypad__pb2.HaltResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoypadStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/JoypadStart',
            joypad__pb2.JoypadStartRequest.SerializeToString,
            joypad__pb2.JoypadStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoypadStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/JoypadStop',
            joypad__pb2.JoypadStopRequest.SerializeToString,
            joypad__pb2.JoypadStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoypadSetScale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/JoypadSetScale',
            joypad__pb2.JoypadSetScaleRequest.SerializeToString,
            joypad__pb2.JoypadSetScaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoypadSetDt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/JoypadSetDt',
            joypad__pb2.JoypadSetDtRequest.SerializeToString,
            joypad__pb2.JoypadSetDtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/GetCurrentPosition',
            joypad__pb2.GetCurrentPositionRequest.SerializeToString,
            joypad__pb2.GetCurrentPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentAngle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/GetCurrentAngle',
            joypad__pb2.GetCurrentAngleRequest.SerializeToString,
            joypad__pb2.GetCurrentAngleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/GetValue',
            joypad__pb2.VarGetRequest.SerializeToString,
            joypad__pb2.VarGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/PutValue',
            joypad__pb2.VarPutRequest.SerializeToString,
            joypad__pb2.VarPutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MotorOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/MotorOn',
            joypad__pb2.MotorOnRequest.SerializeToString,
            joypad__pb2.MotorOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MotorOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/MotorOff',
            joypad__pb2.MotorOffRequest.SerializeToString,
            joypad__pb2.MotorOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandMoveH(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/HandMoveH',
            joypad__pb2.HandMoveHRequest.SerializeToString,
            joypad__pb2.HandMoveHResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandMoveA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/HandMoveA',
            joypad__pb2.HandMoveARequest.SerializeToString,
            joypad__pb2.HandMoveAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MovePose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/MovePose',
            joypad__pb2.MovePoseRequest.SerializeToString,
            joypad__pb2.MovePoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/MoveP',
            joypad__pb2.MovePRequest.SerializeToString,
            joypad__pb2.MovePResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/Move',
            joypad__pb2.MoveRequest.SerializeToString,
            joypad__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakeArm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/TakeArm',
            joypad__pb2.TakeArmRequest.SerializeToString,
            joypad__pb2.TakeArmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GiveArm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/GiveArm',
            joypad__pb2.GiveArmRequest.SerializeToString,
            joypad__pb2.GiveArmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrorCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/GetErrorCount',
            joypad__pb2.GetErrorCountRequest.SerializeToString,
            joypad__pb2.GetErrorCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrorDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/GetErrorDescription',
            joypad__pb2.GetErrorDescriptionRequest.SerializeToString,
            joypad__pb2.GetErrorDescriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/GetErrorInfo',
            joypad__pb2.GetErrorInfoRequest.SerializeToString,
            joypad__pb2.GetErrorInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentErrorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/GetCurrentErrorInfo',
            joypad__pb2.GetCurrentErrorInfoRequest.SerializeToString,
            joypad__pb2.GetCurrentErrorInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobotta.JoyPadControl/ResetError',
            joypad__pb2.ResetErrorRequest.SerializeToString,
            joypad__pb2.ResetErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
